# Generated by Django 5.0.3 on 2024-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('count', models.CharField(max_length=3, verbose_name='Количество людей')),
            ],
        ),
    ]
