# Generated by Django 5.0.3 on 2024-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='Тема')),
                ('comments', models.CharField(max_length=150, null=True, verbose_name='Комментарии')),
                ('data', models.CharField(max_length=70, verbose_name='Сроки проведения')),
                ('link_article', models.CharField(max_length=150, verbose_name='Ссылка на статью')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
